config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  get 'store_books/add_books', to: 'store_books#add_books'
  post 'store_books/:id/add_stock', to: 'store_books#add_stock'
  post 'store_books/:id/remove_stock', to: 'store_books#remove_stock'

  resources :stores
  resources :store_books
  resources :books
  resources :authors

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/author.rb
class Author < ApplicationRecord
  has_many :books

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :author
  has_many :store_books

  scope :not_in_store, ->(store_id) { 
    # Have to write SQL directly as it doesn't seem possible to apply conditions to any ActiveRecord join methods
    # Only return books that don't have a store_book association with a specific store
    left_join_sanitized = ApplicationRecord.sanitize_sql([
      "LEFT JOIN store_books ON (store_books.book_id = books.id AND store_books.store_id = :store_id)",
      { store_id: store_id }
    ])
    joins(left_join_sanitized).where(store_books: { id: nil })
  }
end

app/models/store.rb
class Store < ApplicationRecord
  has_many :store_books

  #after_create_commit -> { broadcast_append_to "stores", partial: "stores/store_list_item", locals: { store: self }, target: "store_list_items" }

  def order_required?
    store_books.out_of_stock.count > 0
  end

end

app/models/store_book.rb
class StoreBook < ApplicationRecord
  belongs_to :book
  belongs_to :store

  scope :out_of_stock, -> { where('count = 0') }

  scope :in_stock, -> { where('count > 0') }

  scope :ordered_by_count, -> { order(count: :asc) }

  def in_stock?
    count > 0
  end

  def self.ordered_by_out_of_stock
    out = self.out_of_stock.to_a
    out.concat(self.in_stock)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController

  def new
    @author = Author.new
  end

  def create
    @author = Author.create(params.require(:author).permit(:first_name, :last_name))
    @authors = Author.all
    render partial: "author_select", locals: { author: @author }
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  before_action :set_book, only: [:edit, :update, :destroy]
  before_action :set_author, only: [:create, :update]

  def index
    @books = Book.all
  end

  def new
    @book = Book.new
    @authors = Author.all
  end

  def create
    Book.create(
      title: book_params[:title], 
      year: book_params[:year],
      author: @author
    )
    redirect_to books_path
  end

  def edit
  end

  def update
    @book.update(
      title: book_params[:title], 
      year: book_params[:year],
      author: @author
    )
    redirect_to books_path
  end

  def destroy
    @book.destroy
    redirect_to books_path
  end

  private

  def set_book
    @book = Book.find(params[:id])
  end

  def set_author
    @author = Author.find(params[:author_id])
  end

  def book_params
    params.require(:book).permit(:title, :year)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @default_store = Store.first
  end
end

app/controllers/store_books_controller.rb
class StoreBooksController < ApplicationController
  before_action :set_store_book, only: [:show, :destroy, :add_stock, :remove_stock]
  before_action :set_store, only: [:create]

  def index
    store = Store.find(params[:store_id])
    @store_books = store.store_books
  end

  def show
  end

  def create
    @book = Book.find(params[:book_id])
    @store_book = @store.store_books.create(book: @book)
  end

  def destroy
    @store = @store_book.store
    @store_book.destroy

    # store_book was removed from store_books/add_books
    # render add_book_list_item
    if params.has_key?(:added)
      render partial: 'store_books/add_book_list_item', locals: { book: @store_book.book, store: @store }
      return
    end

    redirect_to action: 'index', store_id: @store.id
  end

  def add_stock
    @store_book.update(count: @store_book.count + 1)
    render :show
  end

  def remove_stock
    @store_book.update(count: [@store_book.count - 1, 0].max)
    render :show
  end

  def add_books
    @store = Store.find(params[:store_id])
    @books = Book.not_in_store(@store.id)
  end

  private

  def set_store_book
    @store_book = StoreBook.find(params[:id])
  end

  def set_store
    @store = Store.find(params[:store_id])
  end

end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  before_action :set_store, only: [:show, :edit, :update, :destroy]

  def index
    @stores = Store.all
  end

  def show
  end

  def new
    @store = Store.new
  end

  def create
    @store = Store.create(store_params)
    @stores = Store.all
  end

  def edit
  end

  def update
    @store.update(store_params)
    redirect_to store_path(@store.id)
  end

  def destroy
    @store.destroy
    redirect_to stores_path
  end

  private

  def set_store
    @store = Store.find(params[:id])
  end

  def store_params
    params.require(:store).permit(:name)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/store_books_helper.rb
module StoreBooksHelper
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/authors/_author_select.html.erb
<turbo-frame id="book_author" class="flex">

  <% if local_assigns[:author] %>
    <%= select_tag :author_id, options_from_collection_for_select(Author.all, 'id', 'full_name', author.id), prompt: "Select an author" %>
  <% else %>
    <%= select_tag :author_id, options_from_collection_for_select(Author.all, 'id', 'full_name'), prompt: "Select an author" %>
  <% end %>

  <a href="<%= new_author_path %>" data-turbo-frame="_self" class="ml-2 h-full">
    <button>New Author</button>
  </a>

</turbo-frame>

app/views/authors/new.html.erb
<turbo-frame id="book_author">
  <%= form_for @author do |f| %>
    <div class="flex space-x-2 items-center">
      <div class="flex flex-col w-32">
        <%= f.text_field :first_name, placeholder: "First name" %>
      </div>
      <div class="flex flex-col w-32">
        <%= f.text_field :last_name, placeholder: "Last name" %>
      </div>
      <button class="px-2" type="submit">Save Author</button>
    </div>
  <% end %>
</turbo-frame>

app/views/books/_book_list_item.html.erb
<div class="border-b border-neutral-300 pb-2 mb-2">
  <turbo-frame id="book_<%= book.id %>">

    <div class="flex">
      <%= render "shared/book_list_item_info", book: book %>

      <div class="flex flex-grow items-end justify-end space-x-2">
        <%= button_to "Edit", "/books/#{book.id}/edit", method: "get", form: { "data-turbo-frame": "store_display" } %>
        <%= button_to "Delete", "/books/#{book.id}", method: "delete", form: { "data-turbo-frame": "store_display" } %>
      </div>
    </div>

  </turbo-frame>
</div>

app/views/books/_form.html.erb
<div class="mt-2"></div>
<%= form_for @book do |f| %>
  <div class="space-y-2">
    <div class="flex space-x-2">
      <div class="max-w-sm flex-grow">
        <%= f.label :title %>
        <%= f.text_field :title, placeholder: "Book title" %>
      </div>
      <div class="w-32">
        <%= f.label :year %>
        <%= f.number_field :year, placeholder: "Year published" %>
      </div>
    </div>

    <div>
      <%= f.label :author %>
      <div class="flex items-center">
        <%= render partial: "authors/author_select", locals: { author: @book.author } %>
      </div>
    </div>

    <button primary class="mt-4 px-2" type="submit">Save</button>

  </div>
<% end %>

app/views/books/edit.html.erb
<turbo-frame id="store_display">
  <h3>Edit Book</h3>
  <%= render partial: 'form' %>
</turbo-frame>

app/views/books/index.html.erb
<turbo-frame id="store_display">

  <div class="mb-4 flex items-center justify-between">
    <h3>All Books</h3>
    <a href="/books/new" data-turbo-frame="store_display">
      <button primary class="flex items-center">Create Book</button>
    </a>
  </div>

  <div class="mb-2 flex items-center bg-indigo-800 pl-2 py-1">
    <h4 class="font-bold text-neutral-100">Books</h4>
  </div>

  <div class="space-y-2">
    <%= render partial: 'book_list_item', collection: @books, as: :book %>
  </div>

</turbo-frame>

app/views/books/new.html.erb
<turbo-frame id="store_display">
  <h3>New Book</h3>
  <%= render partial: 'form' %>
</turbo-frame>

app/views/home/index.html.erb
<%#= turbo_stream_from "stores" %>

<header class="p-4 bg-indigo-900 flex justify-between items-center">
  <h1 class="text-3xl font-bold text-white">Vention BIM</h1>
  <a href="https://github.com/levidavidmurray/vention-bim" target="_blank" class="text-neutral-100 text-3xl hover:text-neutral-300 active:text-neutral-400">
    <iconify-icon icon="mdi:github"></iconify-icon>
  </a>
</header>

<div class="flex px-4 mt-4 overflow-hidden">

  <%# Bookstore List %>
  <div class="w-72 flex-shrink-0 scrollbar-thin scrollbar-thumb-neutral-400 scrollbar-track-neutral-200 pr-2 mr-8 overflow-y-auto">
    <turbo-frame src="/stores" id="store_list"></turbo-frame>
  </div>

  <%# Selected Bookstore %>
  <div class="flex-grow overflow-y-auto scrollbar-thin scrollbar-thumb-neutral-400 scrollbar-track-neutral-200 pr-2">
    <div class="w-full flex justify-end mb-2">
      <a href="/books" data-turbo-frame="store_display">
        <button primary>View All Books</button>
      </a>
    </div>
    <div class="w-full bg-neutral-200 border-neutral-300 border mb-12 py-4 px-6">
      <% if @default_store.nil? %>
        <turbo-frame src="/stores/new" id="store_display"></turbo-frame>
      <% else %>
        <turbo-frame src="/stores/<%= @default_store.id %>" id="store_display"></turbo-frame>
      <% end %>
    </div>
  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="h-full bg-neutral-100">
  <head>
    <title>VentionBim</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="preconnect" href="https://rsms.me/">
    <link rel="stylesheet" href="https://rsms.me/inter/inter.css">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= vite_client_tag %>
    <%= vite_typescript_tag 'application' %>

    <%= javascript_importmap_tags %>

  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_book_list_item_info.html.erb
<div class="flex flex-col">
  <p class="font-medium text-sm">
    <%= book.title %>
  </p>

  <span class="text-xs text-neutral-600 leading-4">
    <%= book.author.full_name %>
    <span class="mx-0.5">·</span>
    <span class="text-neutral-500"><%= book.year %></span>
  </span>
</div>

app/views/store_books/_add_book_list_item.html.erb
<div class="border-b border-neutral-300 pb-2 mb-2">
  <turbo-frame id="book_<%= book.id %>">

    <div class="flex">
      <%= render "shared/book_list_item_info", book: book %>

      <div class="flex flex-grow items-end justify-end">
        <% if local_assigns[:store_book] %>
          <form action="/store_books/<%= store_book.id %>?added" data-turbo-frame="_self" method="delete" class="inline-block mr-0 ml-auto">
            <button>Remove Book</button>
          </form>
        <% elsif local_assigns[:store] %>
          <form action="/store_books" data-turbo-frame="_self" method="post" class="inline-block mr-0 ml-auto">
            <input type="hidden" name="store_id" value="<%= store.id %>">
            <input type="hidden" name="book_id" value="<%= book.id %>">
            <button>Add Book</button>
          </form>
        <% end %>
      </div>
    </div>

  </turbo-frame>
</div>

app/views/store_books/_store_book.html.erb
<div class="border-b border-neutral-300 pb-2 mb-2">
  <turbo-frame id="store_book_<%= store_book.id %>">

    <%= render "shared/book_list_item_info", book: store_book.book %>

    <div class="relative">

      <div class="flex items-center justify-between">

        <div class="mt-2">
          <div class="inline-block" style="min-width: 74px;">
            <span chip class="<%= store_book.in_stock? ? 'bg-indigo-800' : 'bg-neutral-400' %>">In-stock: <%= store_book.count %></span>
          </div>

          <div class="inline-flex">
            <form action="/store_books/<%= store_book.id %>/remove_stock" data-turbo-frame="_self" method="post">
              <button icon class="border-r-0 justify-center button-square"><iconify-icon icon="ic:baseline-minus"></iconify-icon></button>
            </form>
            <form action="/store_books/<%= store_book.id %>/add_stock" data-turbo-frame="_self" method="post">
              <button icon class="justify-center button-square"><iconify-icon icon="ic:baseline-plus"></iconify-icon></button>
            </form>
          </div>
        </div>

        <form action="/store_books/<%= store_book.id %>" data-turbo-frame="store_books_list" method="delete">
          <button>Remove Book</button>
        </form>

      </div>

    </div>
  </turbo-frame>
</div>

app/views/store_books/_store_books_list.html.erb
<turbo-frame id="store_books_list">
  <%= render store_books %>
</turbo-frame>

app/views/store_books/add_books.html.erb
<turbo-frame id="store_display">
  <div class="mb-4 flex items-center justify-between">
    <h3><%= @store.name %></h3>
    <a href="/stores/<%= @store.id %>" data-turbo-frame="store_display">
      <button primary class="flex items-center">Done</button>
    </a>
  </div>

  <div class="mb-2 flex items-center bg-indigo-800 pl-2 py-1">
    <h4 class="font-bold text-neutral-100">Add Books to <%= @store.name %></h4>
  </div>

  <div class="space-y-2">
    <% for book in @books %>
      <%= render partial: 'add_book_list_item', locals: { book: book, store: @store } %>
    <% end %>
    
  </div>
</turbo-frame>

app/views/store_books/create.html.erb
<%= render partial: 'add_book_list_item', locals: { book: @book, store_book: @store_book } %>

app/views/store_books/index.html.erb
<%= render 'store_books_list', store_books: @store_books.ordered_by_out_of_stock %>

app/views/store_books/show.html.erb
<%= render @store_book %>

app/views/stores/_form.html.erb
<%= form_for @store do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, placeholder: "Bookstore name" %>
  <button primary class="mt-4 px-2" type="submit">Save</button>
<% end %>

app/views/stores/_store.html.erb
<turbo-frame id="store_display">
  <%# Bookstore Name %>
  <div class="mb-4 flex items-center justify-between">
    <h3><%= store.name %></h3>

    <div class="flex space-x-2">
      <a href="/stores/<%= store.id %>/edit" data-turbo-frame="store_display">
        <button class="flex items-center">Edit Store</button>
      </a>
      <a href="/store_books/add_books?store_id=<%= store.id %>" data-turbo-frame="store_display">
        <button primary class="flex items-center">Add Book</button>
      </a>
    </div>
  </div>

  <div class="mb-2 flex items-center bg-indigo-800 pl-2 py-1">
    <h4 class="font-bold text-neutral-100">Books</h4>
  </div>

  <div class="space-y-2">
    <%= render 'store_books/store_books_list', store_books: store.store_books.ordered_by_out_of_stock %>
  </div>
</turbo-frame>

app/views/stores/_store_list.html.erb
<turbo-frame id="store_list">
  <div class="flex items-center justify-between">
    <h2 class="text-xl font-bold mb-2">Bookstores (<%= stores.count %>)</h2>
    <a href="/stores/new" data-turbo-frame="store_display">
      <button primary>
        <iconify-icon icon="ic:baseline-plus"></iconify-icon>
        Add Store
      </button>
    </a>
  </div>

  <div id="store_list_items" class="space-y-2">
    <% for store in stores %>
      <%= render 'store_list_item', store: store %>
    <% end %>
  </div>
</turbo-frame>

app/views/stores/_store_list_item.html.erb
<turbo-stream action="append" target="store_list_items">
  <template>
    <a href="/stores/<%= store.id %>" data-turbo-frame="store_display" class="block border border-neutral-300 bg-neutral-200 px-4 py-2 active:bg-neutral-400">
      <div class="flex justify-between items-center">

        <h4 class="font-semibold"><%= store.name %></h4>

        <% if store.order_required? %>
          <iconify-icon icon="bi:exclamation-circle-fill" class="text-yellow-600"></iconify-icon>
        <% end %>

      </div>
    </a>
  </template>
</turbo-stream>

app/views/stores/create.turbo_stream.erb
<turbo-stream action="replace" target="store_list">
  <template>
    <%= render 'store_list', stores: @stores %>
  </template>
</turbo-stream>

<turbo-stream action="replace" target="store_display">
  <template>
    <%= render 'store', store: @store %>
  </template>
</turbo-stream>

app/views/stores/edit.html.erb
<turbo-frame id="store_display">
  <h3>Edit Store</h3>
  <%= render 'form' %>
</turbo-frame>

app/views/stores/index.html.erb
<%= render 'store_list', stores: @stores %>

app/views/stores/new.html.erb
<turbo-frame id="store_display">
  <h3>Add Store</h3>
  <%= render 'form' %>
</turbo-frame>

app/views/stores/show.html.erb
<%= render 'store', store: @store %>